spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /test
    stream:
      username: guest
      password: guest
    connection-timeout: 1000ms

    # consumer
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
        concurrency: 1
        max-concurrency: 5